// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {models} from '../models';

export function Ctx():Promise<context.Context>;

export function GetConfig():Promise<Record<string, any>>;

export function GetTodayStats():Promise<models.TodaySummary>;

export function ResetStats():Promise<void>;

export function SaveWindowSize(arg1:number,arg2:number):Promise<void>;

export function SetConfig(arg1:Record<string, any>):Promise<Array<string>>;

export function StartDrag():Promise<void>;

export function ToggleLogger():Promise<boolean>;
