// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Ctx() {
  return window['go']['app']['App']['Ctx']();
}

export function GetTodayStats() {
  return window['go']['app']['App']['GetTodayStats']();
}

export function GetWindowSize() {
  return window['go']['app']['App']['GetWindowSize']();
}

export function ResetStats() {
  return window['go']['app']['App']['ResetStats']();
}

export function SaveWindowSize(arg1, arg2) {
  return window['go']['app']['App']['SaveWindowSize'](arg1, arg2);
}

export function StartDrag() {
  return window['go']['app']['App']['StartDrag']();
}

export function ToggleLogger() {
  return window['go']['app']['App']['ToggleLogger']();
}
