// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetDateRangeStats(arg1, arg2) {
  return window['go']['app']['App']['GetDateRangeStats'](arg1, arg2);
}

export function GetStats(arg1) {
  return window['go']['app']['App']['GetStats'](arg1);
}

export function GetSystemFonts() {
  return window['go']['app']['App']['GetSystemFonts']();
}

export function GetTodayStats() {
  return window['go']['app']['App']['GetTodayStats']();
}

export function ResetStats() {
  return window['go']['app']['App']['ResetStats']();
}

export function SaveWindowSize(arg1, arg2) {
  return window['go']['app']['App']['SaveWindowSize'](arg1, arg2);
}

export function SetConfig(arg1) {
  return window['go']['app']['App']['SetConfig'](arg1);
}

export function SetWindowIcon() {
  return window['go']['app']['App']['SetWindowIcon']();
}

export function StartDrag() {
  return window['go']['app']['App']['StartDrag']();
}
