// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {models} from '../models';

export function Ctx():Promise<context.Context>;

export function GetTodayStats():Promise<models.TodaySummary>;

export function StartDrag():Promise<void>;

export function ToggleLogger():Promise<boolean>;
