// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetTodayStats():Promise<models.TodaySummary>;

export function ToggleLogger():Promise<boolean>;
