// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTodayStats() {
  return window['go']['main']['App']['GetTodayStats']();
}

export function StartDrag() {
  return window['go']['main']['App']['StartDrag']();
}

export function ToggleLogger() {
  return window['go']['main']['App']['ToggleLogger']();
}
